### ISSUE TITLE
Not able to simulate the test circuit

### ISSUE THREAD

**Issue by vabzter** [eskiyerli/revEDAsetup#2]
Hi Murat,
I have installed the RevEda tool on Ubuntu. The tool is running properly and I can see all the libs.
But when I try to simulate the tb_inv1, I am getting the following error:
Traceback (most recent call last):
  File "<frozen reveda.wxGui>", line 1190, in onNetlRun
  File "<frozen reveda.wxGui>", line 1358, in netlistCircuit
  File "/usr/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/caduser/simulations/sky130Devices/tb_inv1/tb_inv1_schematic.cir'

Here are some of the snapshots:
![1](https://user-images.githubusercontent.com/77781274/144302036-703ecba4-9210-46fa-b2d3-8dff909495ee.png)

Thanks for your help.
vab

**Comment by eskiyerli** [comment]
Hello, could you please open terminal or text editor tools from the utilities menu on the schematic editor check if there is /home/caduser/simulations/sky130Devices/tb_inv1/tb_inv1_schematic.cir file. It seems that it cannot find the netlist file.

**Comment by vabzter** [comment]
Hi somehow I am not able to copy the schematic file from /home/caduser/sky130Devices/tb_inv1/schematic to /home/caduser/simulations/sky130Devices/tb_inv1
Its saying permission denied

**Comment by eskiyerli** [comment]
You should not need to  copy any netlist. Can you check the simulation path? Under "Setup" menu, you should find "Simulation Root Directory". Make sure that it is set to "/home/caduser/simulations" directory.

**Comment by eskiyerli** [comment]
Hello have you resolved this issue? To help the users, I started writing a tutorial for the use of Revolution EDA. You could find the parts written so far in the repository.

**Comment by vabzter** [comment]
Hi somehow I am not able to copy the schematic file from /home/caduser/sky130Devices/tb_inv1/schematic to /home/caduser/simulations/sky130Devices/tb_inv1
Its saying permission denied


> You should not need to copy any netlist. Can you check the simulation path? Under "Setup" menu, you should find "Simulation Root Directory". Make sure that it is set to "/home/caduser/simulations" directory.

Hi Yes I checked and the simulation path is correct. Also there is no tb_inv1_schematic.cir in the path. Please see the attached screenshots.
![sim_dir](https://user-images.githubusercontent.com/77781274/145673122-285b7dac-8de8-4ead-90ae-860eead56748.png)
![path1](https://user-images.githubusercontent.com/77781274/145673123-d4076590-83fc-4d14-8e00-976e5eaab5a5.png)

**Comment by eskiyerli** [comment]
I can suggest two things:

1. Could you please check the permissions of simulations directory under revEDAsetup directory. It should be readable and writable by everyone:
drwxrwxrwx 3 eskiyerli eskiyerli    4096 Nov  5 13:44  simulations
2. Failing that could you please tell me your OS and I will try to replicate the problem.
Regards,

Murat

**Comment by vabzter** [comment]
Hi there, I check the permissions and they are as below:
![snip](https://user-images.githubusercontent.com/77781274/145687049-a56a32fa-5919-46a3-a3d8-7598ee3006fe.png)
I am using 64-bit Ubuntu 20.04.3 LTS
Thanks and regards,
Vab

**Comment by eskiyerli** [comment]
Could you check the permission not inside the container image but in the host system? 'simulations' directory is in fact in your host system, i.e. Ubuntu.

**Comment by vabzter** [comment]
Hi Yes I checked the file permission under revEDAsetup/simulations

It is drwxrwxr-x 3 vabzter vabzter 4096 Nov 30 18:04 simulation/ 

Then i changed the permissions to read write all

Now its drwxrwxrwx  3 vabzter vabzter   4096 Nov 30 18:04  simulations/

Still its now able to find the .cir file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/caduser/simulations/sky130Devices/tb_inv1/tb_inv1_schematic.cir'

I check the path location in ubuntu. The only file it had is the simState.yaml
Thanks and regards,
Vab

**Comment by eskiyerli** [comment]
Let me setup an Ubuntu installation on a VM and install on it. I will report back asap.

**Comment by eskiyerli** [comment]
I added an Ubuntu installation manual. What you should try is

1. Change to revEDAsetup directory
2. run: 
chmod a+rwx simulations/

Let me know if it works.

**Comment by eskiyerli** [comment]
Is your problem resolved now?

**Comment by vabzter** [comment]
Hi Murat,
I could run the simulations successfully after the chmod which you have suggested.
![output](https://user-images.githubusercontent.com/77781274/146037950-9345f9a6-8d71-4c1a-aafe-8cda7f4b7053.png)

I will do my own test circuits and will let you know.

Please close this ticket

Thanks and regards,
Vab

**Comment by eskiyerli** [comment]
Great. Please let me know of any and all feedback you might have.
