### ISSUE TITLE
Setup issue in ubuntu 20.04

### ISSUE THREAD

**Issue by engrvip** [eskiyerli/revEDAsetup#4]
Hi Murat,

I followed all steps shared at below link for setting up tools on Ubunut 20.04.
https://reveda.eu/pages/ubuntuInstallation 

But it is ending with error:  podman-compose: command not found

Screenshot is attached for reference. Please suggest how to resolve it.

Regards
Vipul

**Comment by eskiyerli** [comment]
Hello,
I don't have access now to Ubuntu machine but I could setup in a VM. Have you installed podman-compose? If not, could you try to install it or alternatively docker-compose? Then you could change the command to docker-compose.

**Comment by engrvip** [comment]
Hi,
After updating some ubuntu packages I was able to run tool using podman-compose itself as per steps mentioned in ubunutu installation guide.

**Comment by eskiyerli** [comment]
Good news. Let me know if you have any further problems.
