### ISSUE TITLE
Problem adding net in direct plot

### ISSUE THREAD

**Issue by engrvip** [eskiyerli/revEDAsetup#5]
Hi Murat,

As shown in attached GIF, I am not able to select net under "direct plot" option or seletc output net in noise analysis. I tried following steps mentioned in tutorial on website but it didn't helped. Can you please clarify how to directly select net on schematic signal plot. 
![node](https://user-images.githubusercontent.com/84322258/162607192-9d7968ae-b567-4f57-a647-c65105e409c3.gif)
l
 
Regards
Vipul

**Comment by eskiyerli** [comment]
Hello,

I think the problem is that you need to double click on "select a Net/Instance" entry, then select the net, click back on entry line and press "ESC". It is a bit convoluted as Glade does not emit too many signals.

**Comment by engrvip** [comment]
Thanks Murat, issue is resolved now.
