### ISSUE TITLE
Use all sky130 devices 

### ISSUE THREAD

**Issue by engrvip** [eskiyerli/revEDAsetup#6]
Hi Murat, 

I wanted to create a new schematic hence check what all other devices are available in sky130 pdk. At present only few devices are visible in "sky130Devices" library inside Glade.

How to access other available devices ?

Vipul

**Comment by eskiyerli** [comment]
Hello Vipul,

This is a preview release. Thus, only a few most used devices were created in the PDK. It requires both conversion of model libraries, symbols with callback functions, and creation of layout parametric cells. If there is a demand and a customer pays for it, the whole PDK could be created.

**Comment by eskiyerli** [comment]
Closing the issue.
